### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by thesourcerer8** [0ffffffffh/dragondance#1]
Could you provide some information about the fileformats?
I generated .idc scripts (e.g. http://www2.futureware.at/~philipp/ssd/colors.zip ) from coverage information in the past, and would like to switch to dragondance instead.

**Comment by 0ffffffffh** [comment]
sure I can

let me describe my pintool's coverage file format. because that is quite simple than drcov's format. so you can write conversion script for it. 

first, the coverage output file begins with it's identification string. that should be

**DDPH-PINTOOL**

then comes the total entry count and loaded module count information. the format should be

**EntryCount: %d, ModuleCount: %d**  

in your case, EntryCount can be half of the total count of the SetColor lines. Why half of it? Because your idc script does coloring two different part for the same offset. SetColor(off,1,color) and SetColor(off,2,color) 1 is for CIC_ITEM and 2 is for CIC_FUNC for IDA. you should skip second SetColor.

Module count can be 1. That is for the executable that you working on.

third,

module information block. module information block should be begins with identification string. and it should be

**MODULE_TABLE**

then you can put module information. so in your case there should be single dummy entry. module information format should be like this:

_[MODULE_ID], [MODULE_BASE], [MODULE_END], [PATH]_

you can set this line with a dummy entry but should be valid for your binary that you working on

you write something like so

1, 0x00000000, 0x100000000, your_executable_path

that would be enough for module entry. but i recommend that you supply the real image's base and end. that will not cause any problem at the moment but i might use (and I will) the module address range info. when I do that you will be experienced problem for sure.


fourth,

entry identification string comes in and it should be

ENTRY_TABLE

after you put the id string line, next data output will be going as binary format.

binary data consist of a blockentry structure. blockentry structure looks like this

blockentry {
rangeStartOffset : 4 Bytes
rangeSize : 2 Bytes
moduleId : 2 Bytes
instructionCount: 4 Bytes
}

so you have to fill your data for that structure.

in your case rangeStartOffset will be your SetColor offset value

as far I see you worked on RISC based instruction set. 

for example

SetColor(0x000000e0,1,mycolor);
SetColor(0x000000e0,2,mycolor);
SetColor(0x000000e4,1,mycolor);
SetColor(0x000000e4,2,mycolor);
SetColor(0x000000e8,1,mycolor);
SetColor(0x000000e8,2,mycolor);

these offsets are fixed and hints that they are RISC based instructions.

so the rangeSize won't be a problem. you can set this value 4, (32 bit fixed instruction size)

moduleId, is should be 1 (remember module info section)

instructionCount  can be 0 or in your case can be 1.

so the above example can be construct like so

blockentry {
rangeStartOffset : 0xe0
rangeSize : 0x4
moduleId : 0x1
instructionCount: 0x1
}
,
blockentry {
rangeStartOffset : 0xe4
rangeSize : 0x4
moduleId : 0x1
instructionCount: 0x1
}
,
blockentry {
rangeStartOffset : 0xe8
rangeSize : 0x4
moduleId : 0x1
instructionCount: 0x1
}



your idc data can be converted to the dragondance's coverage file format except the color value. unfortunally, dragondance can't be take color value directly. it uses it's colorization system for coverage painting.

and that is the example ddph's coverage output 

example coverage file content.

DDPH-PINTOOL
EntryCount: 231234, ModuleCount: 1

MODULE_TABLE
1, 0x7ff662320000, 0x7ff662326fff, D:\Tools\coveragetools\test.exe

ENTRY_TABLE
[BINARY_DATA]
