### ISSUE TITLE
help support newer versions of Ghidra

### ISSUE THREAD

**Issue by janbbeck** [0ffffffffh/dragondance#16]
I would like some documentation added as to how to make a release.
Downloading the `master` as .zip file will not install in any version of `Ghidra`.
The Releases page only has a release for `Ghidra` 9.0.2. That will install ok, but refuse to install on later or earlier versions of `Ghidra`.

So, some information please and maybe a release for a later `Ghidra` version.

**Comment by 0ffffffffh** [comment]
Ghidra has a strange behavior for the extensions. I don't know why but ghidra wants extensions version number must have match with the version of actively running ghidra exactly. Although there is no technical obstacle to run in the next version of ghidra. 

This issue occupies a place in my mind always, so i'm looking for easy, automated solution for this. (Maybe an auto repack for the existed release idk)  But i can't say that i have found one at the moment. But i think i can write-out some hint to make a release or something like that. I have labeled this issue as enhancement.

**Comment by janbbeck** [comment]
Ok, I am having the following issue with installation:
- If I change `extension.properties` in `ghidra_9.0.2_PUBLIC_20190915_dragondance.zip` to version number 9.1.2 it installs fine and works as expected in 9.1.2

-if I try the same with the latest master.zip from github, it installs fine in the main ghidra window, but fails to show up in the code browser window. When going to file-configure in the code browser window and clicking on the little plug symbol, dragondance is missing from the list.

deinstalling master and reinstalling the `ghidra_9.0.2_PUBLIC_20190915_dragondance.zip` brings the dragondance back to the list.

How do I install `master`?

**Comment by 0ffffffffh** [comment]
@janbbeck hi. First I'm sorry for reply late. I was busy for past few days.

I'm not sure ghidra would use plain java code like ghidra script. But to able to install the dragondance as an extension you have to compile and pack it. As far I know ghidra expects compiled .jar file in the extension package.

To do that, you need Eclipse IDE and Ghidra eclipse integration plugin called GhidraDev plugin for Eclipse. Then you need initiate the compile and packing process using GhidraDev plugin. It will compile and pack automatically and generates the extension zip package. 

So that sounds a bit painful but as far I read from the ghidra plugin dev documentation this is the recommended way to build ghidra extension. Of course it can be compile and generate the package manually but it takes some time.

**Comment by janbbeck** [comment]
Thanks a lot. That was very helpful. You don't actually need eclipse, just gradle. Let me make a PR for the documentation
