### ISSUE TITLE
Error at installation

### ISSUE THREAD

**Issue by sebdraven** [0ffffffffh/dragondance#8]
When I try to install ghidra_9.0.2_PUBLIC_20190915_dragondance.zip in ghidra I've an error 
![Capture d’écran du 2019-12-18 15-40-02](https://user-images.githubusercontent.com/1478484/71095332-b308a080-21ac-11ea-9c1d-385c1e770ca2.png)

**Comment by 0ffffffffh** [comment]
probably you are using a version other than Ghidra 9.0.2. Because Ghidra wants version of the extensions have matched exactly with it's own version. Even if you are using higher version of ghidra than the extension's. 

you can try this;

open the plugin package with your favorite unzip app. get in the dragondance folder
and open the file named "extension.properties" with a text editor. 

change version number (9.0.2) with your ghidra version. for example if you are using ghidra 9.1 that should be

version=9.1

save the file and update the extension package with the modified file.

you must install the extension successfully and able to use it. if you are using ghidra newer than 9.0.2, probably you'll be fine with it.

**Comment by sebdraven** [comment]
Rename the version in extension properties don't resolve the issue, i decide to use ghidra 9.0.2 but I've another problem. the plugin loads the cover file but it's no result.
![Capture d’écran du 2019-12-19 09-52-36](https://user-images.githubusercontent.com/1478484/71159076-53aa9f00-2245-11ea-82d8-ca7b7735ed45.png)

**Comment by 0ffffffffh** [comment]
seemed it keep loading something. So I need some information about that issue

What coverage collection tool (and version) did you use to collect coverage data?
What's was your collection mode is? (Plain or binary)
What's your OS

Dragondance should have generated a log file in the ghidra root directory named "dragondance.log"
could you share that log file with me?
__
Ps for first issue. Just for inform you. I have tested the trick that I suggested you within the Ghidra 9.1, and it worked well. Maybe different things prevents to install.

**Comment by sebdraven** [comment]
Ok thanks for the feedback I retry. :)

The version of tools is version 7.91.18243 of DynamoRio on Windows.

**Comment by sebdraven** [comment]
Ok the installation of the plugins with your trick it's ok :) So I close this issue. Thanks for you support !
